server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: false
    openfeign:
      enabled: true
      client:
        config:
          auth-service:
            connectTimeout: 5000
            readTimeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
    build:
      enabled: true
info:
  app:
    name: API Gateway
    description: Routes and authenticates requests for microservices
    version: 1.0-SNAPSHOT
gateway:
  secret: my-gateway-secret-123