server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_orders?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
    build:
      enabled: true
info:
  app:
    name: Order Service
    description: Manages user authentication and profiles
    version: 1.0-SNAPSHOT